# Generated by Django 3.0.3 on 2020-02-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('duree', models.IntegerField(default=0, verbose_name='Duree estimee')),
                ('temps_allouee', models.IntegerField(verbose_name='Temps allouee')),
                ('besoins', models.TextField()),
                ('est_valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Utilisateur')),
            ],
            bases=('hub.utilisateur',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hub.Utilisateur')),
            ],
            bases=('hub.utilisateur',),
        ),
        migrations.CreateModel(
            name='MembershipInProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_allocated_by_member', models.IntegerField(verbose_name='Temps a.llouee')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Projet')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_owner', to='hub.Etudiant'),
        ),
        migrations.AddField(
            model_name='projet',
            name='particpants',
            field=models.ManyToManyField(blank=True, related_name='les_membres', through='hub.MembershipInProject', to='hub.Etudiant'),
        ),
        migrations.AddField(
            model_name='projet',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_coach', to='hub.Coach'),
        ),
    ]
